scaffold for cars
Laxmi-Pasi/GoCars pull request #1
Opened 2022-07-22 10:04 UTC by chitrak-bhatt

2022-07-22 12:30 UTC, neshmapatel-simformsolutions requested changes

2022-07-22 12:30 UTC, neshmapatel-simformsolutions commented on app/models/car.rb
> +  enum engine_type: {
you can simply define as;
enum engine_type: [:petrol, :diesel, :hybrid, :ev ]

2022-07-22 12:30 UTC, neshmapatel-simformsolutions commented on app/models/car.rb
> +    Hatchback: 0,
same as above

2022-07-22 12:30 UTC, neshmapatel-simformsolutions commented on app/models/car.rb
> +    Manual: 0,
here as well.

2022-07-25 04:49 UTC, chitrak-bhatt commented on app/models/car.rb
> +    Hatchback: 0,
Done

2022-07-25 06:48 UTC, neshmapatel-simformsolutions commented on app/assets/stylesheets/custom.css
> +}
add a new line at EOF.

2022-07-25 06:53 UTC, chitrak-bhatt commented on app/assets/stylesheets/custom.css
> +}
Done

2022-07-25 06:54 UTC, neshmapatel-simformsolutions approved these changes

2022-07-25 07:04 UTC, merged